# Generated by Django 5.2.16 on 2026-07-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('view_student_dashboard', 'Can view student dashboard'), ('view_student_list', 'Can view student list')]},
        ),
    ]
