# Generated by Django 5.2.16 on 2026-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
